### ISSUE TITLE
Enums generation

### ISSUE THREAD

**Issue by SlayerDF** [TinkoffCreditSystems/swagger-types-generator#2]
For now the generator converts enums
```Yaml
TradeStatus:
  type: string
  enum:
    - NormalTrading
    - NotAvailableForTrading

OperationType:
  type: string
  enum:
    - Buy
    - Sell
```
into empty objects
```TypeScript
type TradeStatus = {};

type OperationType = {};
```

I've made a fix  #1 for it to convert enums into correct types
```TypeScript
type TradeStatus = 'NormalTrading' | 'NotAvailableForTrading';

type OperationType = 'Buy' | 'Sell';
```
